// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/queue.proto

package netinternal

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnqueuRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       []byte                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnqueuRequest) Reset() {
	*x = EnqueuRequest{}
	mi := &file_proto_queue_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnqueuRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnqueuRequest) ProtoMessage() {}

func (x *EnqueuRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_queue_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnqueuRequest.ProtoReflect.Descriptor instead.
func (*EnqueuRequest) Descriptor() ([]byte, []int) {
	return file_proto_queue_proto_rawDescGZIP(), []int{0}
}

func (x *EnqueuRequest) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

type EnqueuRequestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnqueuRequestResponse) Reset() {
	*x = EnqueuRequestResponse{}
	mi := &file_proto_queue_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnqueuRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnqueuRequestResponse) ProtoMessage() {}

func (x *EnqueuRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_queue_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnqueuRequestResponse.ProtoReflect.Descriptor instead.
func (*EnqueuRequestResponse) Descriptor() ([]byte, []int) {
	return file_proto_queue_proto_rawDescGZIP(), []int{1}
}

func (x *EnqueuRequestResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ObserveQueueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConsumerId    uint64                 `protobuf:"varint,1,opt,name=consumerId,proto3" json:"consumerId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObserveQueueRequest) Reset() {
	*x = ObserveQueueRequest{}
	mi := &file_proto_queue_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObserveQueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObserveQueueRequest) ProtoMessage() {}

func (x *ObserveQueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_queue_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObserveQueueRequest.ProtoReflect.Descriptor instead.
func (*ObserveQueueRequest) Descriptor() ([]byte, []int) {
	return file_proto_queue_proto_rawDescGZIP(), []int{2}
}

func (x *ObserveQueueRequest) GetConsumerId() uint64 {
	if x != nil {
		return x.ConsumerId
	}
	return 0
}

type QueueMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       []byte                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueMessage) Reset() {
	*x = QueueMessage{}
	mi := &file_proto_queue_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueMessage) ProtoMessage() {}

func (x *QueueMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_queue_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueMessage.ProtoReflect.Descriptor instead.
func (*QueueMessage) Descriptor() ([]byte, []int) {
	return file_proto_queue_proto_rawDescGZIP(), []int{3}
}

func (x *QueueMessage) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

var File_proto_queue_proto protoreflect.FileDescriptor

const file_proto_queue_proto_rawDesc = "" +
	"\n" +
	"\x11proto/queue.proto\")\n" +
	"\rEnqueuRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\fR\amessage\"1\n" +
	"\x15EnqueuRequestResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"5\n" +
	"\x13ObserveQueueRequest\x12\x1e\n" +
	"\n" +
	"consumerId\x18\x01 \x01(\x04R\n" +
	"consumerId\"(\n" +
	"\fQueueMessage\x12\x18\n" +
	"\amessage\x18\x01 \x01(\fR\amessage2x\n" +
	"\fQueueService\x121\n" +
	"\aEnqueue\x12\x0e.EnqueuRequest\x1a\x16.EnqueuRequestResponse\x125\n" +
	"\fObserveQueue\x12\x14.ObserveQueueRequest\x1a\r.QueueMessage0\x01B#Z!ashishkujoy/queue/net;netinternalb\x06proto3"

var (
	file_proto_queue_proto_rawDescOnce sync.Once
	file_proto_queue_proto_rawDescData []byte
)

func file_proto_queue_proto_rawDescGZIP() []byte {
	file_proto_queue_proto_rawDescOnce.Do(func() {
		file_proto_queue_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_queue_proto_rawDesc), len(file_proto_queue_proto_rawDesc)))
	})
	return file_proto_queue_proto_rawDescData
}

var file_proto_queue_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_queue_proto_goTypes = []any{
	(*EnqueuRequest)(nil),         // 0: EnqueuRequest
	(*EnqueuRequestResponse)(nil), // 1: EnqueuRequestResponse
	(*ObserveQueueRequest)(nil),   // 2: ObserveQueueRequest
	(*QueueMessage)(nil),          // 3: QueueMessage
}
var file_proto_queue_proto_depIdxs = []int32{
	0, // 0: QueueService.Enqueue:input_type -> EnqueuRequest
	2, // 1: QueueService.ObserveQueue:input_type -> ObserveQueueRequest
	1, // 2: QueueService.Enqueue:output_type -> EnqueuRequestResponse
	3, // 3: QueueService.ObserveQueue:output_type -> QueueMessage
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_queue_proto_init() }
func file_proto_queue_proto_init() {
	if File_proto_queue_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_queue_proto_rawDesc), len(file_proto_queue_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_queue_proto_goTypes,
		DependencyIndexes: file_proto_queue_proto_depIdxs,
		MessageInfos:      file_proto_queue_proto_msgTypes,
	}.Build()
	File_proto_queue_proto = out.File
	file_proto_queue_proto_goTypes = nil
	file_proto_queue_proto_depIdxs = nil
}
